# Generated by Django 4.0.4 on 2022-05-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='name',
            field=models.CharField(default='Null', max_length=200),
        ),
    ]
