# Generated by Django 4.0.5 on 2022-06-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_skill_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='PBI_articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Article_title', models.CharField(max_length=200)),
                ('Article_date', models.DateField()),
                ('Article_short_text', models.TextField(blank=True, null=True)),
                ('Aricle_list_tags', models.TextField(blank=True, null=True)),
                ('Article_post_link', models.TextField()),
            ],
        ),
    ]
